add exec sh

diff --git a/pinpoint/charts/pinpoint-hbase/templates/configmap.yaml b/pinpoint/charts/pinpoint-hbase/templates/configmap.yaml
--- a/pinpoint/charts/pinpoint-hbase/templates/configmap.yaml
+++ b/pinpoint/charts/pinpoint-hbase/templates/configmap.yaml
@@ -17,6 +17,21 @@ data:
 
     CONFIG_DIR="/tmp/hbase-config"
 
+    for f in hbase-site.xml hbase-env.sh; do
+      if [[ -e ${CONFIG_DIR}/$f ]]; then
+        cp ${CONFIG_DIR}/$f $HBASE_PREFIX/conf/$f
+      else
+        echo "ERROR: Could not find $f in $CONFIG_DIR"
+        exit 1
+      fi
+    done
+
+    exec /usr/local/bin/initialize-hbase.sh
+
+    until find ${HBASE_PREFIX}/logs -mmin -1 | egrep -q '.*'; echo "`date`: Waiting for logs..." ; do sleep 2 ; done
+    tail -F ${HBASE_PREFIX}/logs/* &
+    while true; do sleep 1000; done
+
   hbase-env.sh: |
     # Extra Java runtime options.
     # Below are what we set by default.  May only work with SUN JVM.
